
server:
  port: 8090

spring:
  security:
    user:
      name: admin
      password: 123456
  rabbitmq:
    host: localhost
    port: 5672
    username: bilgeadmin
    password: bilge!
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  datasource:
    username: 'postgres'
    password: 'root'
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/AuthDB'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


#Jwt


secretkey: ${secretkey}
audience:  ${audience}
issuer:    ${issuer}

redis:
  host: localhost
  port: 6379

myapplication:
  feign:
    user: http://localhost:8092/api/v1

rabbitmq:
  exchange-auth: auth-exchange
  bindingKey: activated-key
  queueActivated: activated-queue
  userUpdateQueue: user-update-queue