server:
  port: ${elastic-port}

spring:
  rabbitmq:
    host: ${rabbitmq-host}
    port: ${rabbitmq-port}
    username: ${rabbitmq-username}
    password: ${rabbitmq-password}
  zipkin:
    enabled: true
    base-url: ${zipkin-url}
    service:
      name: elastic-service
  elasticsearch:
    uris: ${elastic-service-url}

secretkey: ${secretkey}
audience: ${audience}
issuer: ${issuer}

rabbitmq:
  userUpdateQueueElastic: ${rabbitmq-userUpdateQueueElastic}

myapplication:
  feign:
    user: ${myapplication-feign-user}
    auth: ${myapplication-feign-auth}