server:
  port: ${post-port}

spring:
  data:
    mongodb:
      host: ${db_mongo_host}
      port: ${db_mongo_port}
      database: ${db_mongo_postdb}
      username: ${db_mongo_username}
      password: ${db_mongo_password}
  rabbitmq:
    host: ${rabbitmq-host}
    port: ${rabbitmq-port}
    username: ${rabbitmq-username}
    password: ${rabbitmq-password}
  zipkin:
    enabled: true
    base-url: ${zipkin-url}
    service:
      name: post-service


#Jwt
secretkey: ${secretkey}
audience: ${audience}
issuer: ${issuer}

myapplication:
  feign:
    auth: ${myapplication-feign-auth}
    elastic: ${myapplication-feign-elastic}
    user: ${myapplication-feign-user}