server:
  port: 8093

spring:
  data:
    mongodb:
      host: 34.171.58.132
      port: 14606
      database: SMPostDB
      username: bilgeuser
      password: "bilge!!**"
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: post-service


#Jwt
secretkey: ${secretkey}
audience:  ${audience}
issuer:    ${issuer}

myapplication:
  feign:
    auth: http://localhost:8090/api/v1
    elastic: http://localhost:8099/api/v1
    user: http://localhost:8092/api/v1