server:
  port: 8092



spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service

  datasource:
    username: 'postgres'
    password: 'root'
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5432/UserProfileDB'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



#Jwt
secretkey: ${secretkey}
audience:  ${audience}
issuer:    ${issuer}


redis:
  host: localhost
  port: 6379


myapplication:
  feign:
    auth: http://localhost:8090/api/v1
    elastic: http://localhost:8099/api/v1